Server:
  RunMode: debug
  HttpPort: 9999
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  DefaultContextTimeout: 60 # s
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log

  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:9999/static
  UploadImageMaxSize: 5  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Database:
  DBType: mysql
  Username: root  # 填写你的数据库账号
  Password: 123456  # 填写你的数据库密码
  Host: 127.0.0.1:3308
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConnects: 10
  MaxOpenConnects: 30

JWT:
  Secret: justpp
  Issuer: justpp
  Expire: 7200

Email:
  Host: smtp.qq.com
  Port: 465
  UserName: xxxx@qq.com
  Password: xxxxxxxx
  IsSSL: true
  From: xxxx@qq.com
  To:
    - xxxx@qq.com